import type { Adjustments } from './adjustments';

export type PresetGroup = 'Cinematic' | 'Vintage' | 'B&W' | 'Modern' | 'Instagram';

export interface Preset {
  id: string;
  name: string;
  group: PresetGroup;
  patch: Partial<Adjustments>;
}

/**
 * Single source of truth for the colored swatch each preset group uses
 * across the desktop rail and the mobile tools sheet.
 */
export const GROUP_HUE: Record<PresetGroup, string> = {
  Cinematic: 'var(--color-tag-cinematic)',
  Vintage:   'var(--color-tag-vintage)',
  Modern:    'var(--color-tag-modern)',
  'B&W':     'var(--color-tag-bw)',
  Instagram: 'var(--color-tag-instagram)',
};

export const PRESETS: Preset[] = [
  {
    id: 'cine-teal-orange',
    name: 'Teal & Orange',
    group: 'Cinematic',
    patch: {
      exposure: .2,
      contrast: 15,
      highlights: -20,
      shadows: 25,
      whites: 10,
      blacks: -15,
      vibrance: 20,
      saturation: -10,
      splitShadows: '#2A6F87',
      splitHighlights: '#E0A06A',
      splitAmount: 60,
      splitBalance: 0,
    },
  },
  {
    id: 'cine-nocturne',
    name: 'Nocturne',
    group: 'Cinematic',
    patch: {
      exposure: -.3,
      contrast: 25,
      highlights: -35,
      shadows: -20,
      whites: -15,
      blacks: -25,
      temperature: -15,
      vibrance: -15,
      vignetteAmount: -35,
      vignetteFeather: 70,
    },
  },
  {
    id: 'cine-faded-film',
    name: 'Faded Film',
    group: 'Cinematic',
    patch: {
      exposure: .1,
      contrast: -25,
      highlights: -10,
      shadows: 25,
      whites: -20,
      blacks: 30,
      temperature: 8,
      vibrance: -5,
      curves: {
        rgb: [
          { x: 0, y: .08 },
          { x: 1, y: .92 },
        ],
        red: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        green: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        blue: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
      },
    },
  },
  {
    id: 'vintage-kodak',
    name: 'Kodak Gold',
    group: 'Vintage',
    patch: {
      temperature: 18,
      tintShift: 5,
      exposure: .15,
      contrast: 10,
      highlights: -15,
      shadows: 10,
      vibrance: 15,
      saturation: -5,
      grain: 12,
    },
  },
  {
    id: 'vintage-polaroid',
    name: 'Polaroid',
    group: 'Vintage',
    patch: {
      temperature: 10,
      contrast: -15,
      highlights: -20,
      shadows: 30,
      whites: 10,
      vibrance: -10,
      saturation: -15,
      sepia: 15,
      vignetteAmount: -20,
    },
  },
  {
    id: 'modern-vibrant',
    name: 'Vibrant',
    group: 'Modern',
    patch: {
      exposure: .15,
      contrast: 20,
      highlights: -15,
      shadows: 20,
      whites: 5,
      blacks: -10,
      vibrance: 35,
      saturation: 10,
      clarity: 15,
    },
  },
  {
    id: 'modern-clean',
    name: 'Clean Light',
    group: 'Modern',
    patch: {
      exposure: .25,
      contrast: 5,
      highlights: -10,
      shadows: 15,
      whites: 8,
      vibrance: 10,
      sharpenAmount: 25,
    },
  },
  {
    id: 'modern-matte',
    name: 'Matte',
    group: 'Modern',
    patch: {
      contrast: -20,
      highlights: -25,
      shadows: 35,
      whites: -10,
      blacks: 20,
      vibrance: -5,
    },
  },
  {
    id: 'bw-classic',
    name: 'Classic',
    group: 'B&W',
    patch: {
      blackAndWhite: true,
      contrast: 15,
      highlights: -10,
      shadows: 10,
      whites: 5,
      blacks: -5,
    },
  },
  {
    id: 'bw-high-contrast',
    name: 'High Contrast',
    group: 'B&W',
    patch: {
      blackAndWhite: true,
      contrast: 40,
      highlights: -25,
      shadows: -10,
      whites: 20,
      blacks: -30,
      clarity: 25,
    },
  },
  {
    id: 'bw-silver',
    name: 'Silver',
    group: 'B&W',
    patch: {
      blackAndWhite: true,
      contrast: -10,
      highlights: -15,
      shadows: 25,
      vignetteAmount: -15,
    },
  },

  // Instagram-flavoured looks. Tuned approximations of the iconic filters;
  // not literal LUTs but reproductions of the dominant tone + grading move.
  {
    id: 'ig-clarendon',
    name: 'Clarendon',
    group: 'Instagram',
    patch: {
      exposure: .15,
      contrast: 20,
      highlights: 5,
      shadows: -10,
      whites: 15,
      blacks: -10,
      vibrance: 25,
      saturation: 10,
      temperature: -8,
      clarity: 10,
    },
  },
  {
    id: 'ig-gingham',
    name: 'Gingham',
    group: 'Instagram',
    patch: {
      exposure: .25,
      contrast: -20,
      highlights: -25,
      shadows: 35,
      whites: -10,
      blacks: 25,
      vibrance: -20,
      saturation: -15,
      temperature: 4,
      splitShadows: '#3F3852',
      splitHighlights: '#F2E7CE',
      splitAmount: 45,
    },
  },
  {
    // Per-channel transfer curves measured from a reference Lark render
    // (input -> output, sampled at 1/8 stops). Reproduces the filter to
    // ~1.7 levels/channel through the engine's curve op. Signature: lifted
    // blacks (faded), near-linear warm mids, blue highlights capped ~0.91.
    id: 'ig-lark',
    name: 'Lark',
    group: 'Instagram',
    patch: {
      vibrance: 8,
      curves: {
        rgb: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        red: [
          { x: 0, y: .077 }, { x: .125, y: .201 }, { x: .251, y: .331 },
          { x: .376, y: .459 }, { x: .502, y: .601 }, { x: .627, y: .726 },
          { x: .753, y: .853 }, { x: .878, y: .974 }, { x: 1, y: 1 },
        ],
        green: [
          { x: 0, y: .082 }, { x: .125, y: .214 }, { x: .251, y: .335 },
          { x: .376, y: .466 }, { x: .502, y: .594 }, { x: .627, y: .724 },
          { x: .753, y: .855 }, { x: .878, y: .987 }, { x: 1, y: 1 },
        ],
        blue: [
          { x: 0, y: .075 }, { x: .125, y: .194 }, { x: .251, y: .316 },
          { x: .376, y: .452 }, { x: .502, y: .579 }, { x: .627, y: .724 },
          { x: .753, y: .859 }, { x: .878, y: .910 }, { x: 1, y: .910 },
        ],
      },
    },
  },
  {
    // Measured from a reference Calderon render. Reproduces to ~2.4
    // levels/channel. Signature: strong warm contrast lift on R/G,
    // blue highlights capped ~0.98.
    id: 'ig-calderon',
    name: 'Calderon',
    group: 'Instagram',
    patch: {
      curves: {
        rgb: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        red: [
          { x: 0, y: .006 }, { x: .125, y: .158 }, { x: .251, y: .318 },
          { x: .376, y: .474 }, { x: .502, y: .657 }, { x: .627, y: .809 },
          { x: .753, y: .964 }, { x: .878, y: 1 }, { x: 1, y: 1 },
        ],
        green: [
          { x: 0, y: .008 }, { x: .125, y: .164 }, { x: .251, y: .302 },
          { x: .376, y: .465 }, { x: .502, y: .619 }, { x: .627, y: .773 },
          { x: .753, y: .930 }, { x: .878, y: 1 }, { x: 1, y: 1 },
        ],
        blue: [
          { x: 0, y: .001 }, { x: .125, y: .127 }, { x: .251, y: .269 },
          { x: .376, y: .425 }, { x: .502, y: .582 }, { x: .627, y: .749 },
          { x: .753, y: .910 }, { x: .878, y: .976 }, { x: 1, y: .976 },
        ],
      },
    },
  },
  {
    id: 'ig-lofi',
    name: 'Lo-Fi',
    group: 'Instagram',
    patch: {
      exposure: -.1,
      contrast: 35,
      highlights: -20,
      shadows: -15,
      whites: 10,
      blacks: -25,
      vibrance: 30,
      saturation: 20,
      clarity: 25,
      vignetteAmount: -25,
    },
  },
  {
    id: 'ig-nashville',
    name: 'Nashville',
    group: 'Instagram',
    patch: {
      exposure: .15,
      contrast: -10,
      highlights: -15,
      shadows: 30,
      whites: 5,
      blacks: 15,
      vibrance: 5,
      saturation: -10,
      temperature: 15,
      tintShift: 18,
      splitShadows: '#522E45',
      splitHighlights: '#F5BFA3',
      splitAmount: 55,
      grain: 8,
    },
  },
  {
    id: 'ig-valencia',
    name: 'Valencia',
    group: 'Instagram',
    patch: {
      exposure: .1,
      contrast: -8,
      highlights: -10,
      shadows: 20,
      whites: 5,
      vibrance: -10,
      saturation: -15,
      temperature: 14,
      sepia: 18,
      vignetteAmount: -10,
    },
  },
  {
    id: 'ig-xpro',
    name: 'X-Pro II',
    group: 'Instagram',
    patch: {
      exposure: -.05,
      contrast: 30,
      highlights: -25,
      shadows: -10,
      whites: 10,
      blacks: -20,
      vibrance: 20,
      saturation: 15,
      temperature: 10,
      splitShadows: '#1E2A4A',
      splitHighlights: '#E8AB4F',
      splitAmount: 50,
      vignetteAmount: -45,
      vignetteFeather: 70,
    },
  },
  {
    id: 'ig-hudson',
    name: 'Hudson',
    group: 'Instagram',
    patch: {
      exposure: .15,
      contrast: 5,
      highlights: -10,
      shadows: 15,
      vibrance: -5,
      temperature: -20,
      tintShift: -8,
      splitHighlights: '#A8C9DD',
      splitShadows: '#2E3F50',
      splitAmount: 40,
      vignetteAmount: -15,
    },
  },
  {
    id: 'ig-1977',
    name: '1977',
    group: 'Instagram',
    patch: {
      exposure: .1,
      contrast: -15,
      highlights: -20,
      shadows: 25,
      blacks: 30,
      whites: -10,
      vibrance: -5,
      saturation: -10,
      temperature: 12,
      tintShift: 22,
      splitHighlights: '#E89B7C',
      splitShadows: '#5C2C2C',
      splitAmount: 50,
      grain: 12,
    },
  },
  {
    id: 'ig-mayfair',
    name: 'Mayfair',
    group: 'Instagram',
    patch: {
      exposure: .1,
      contrast: 10,
      highlights: -10,
      shadows: 15,
      vibrance: 15,
      saturation: 5,
      temperature: 6,
      splitHighlights: '#F3C8B0',
      splitShadows: '#4A3640',
      splitAmount: 35,
      vignetteAmount: -25,
      vignetteFeather: 60,
    },
  },
  {
    id: 'ig-inkwell',
    name: 'Inkwell',
    group: 'Instagram',
    patch: {
      blackAndWhite: true,
      contrast: 25,
      highlights: -15,
      shadows: 5,
      whites: 15,
      blacks: -20,
      clarity: 15,
    },
  },
];
